-- Create the STUDENT table
CREATE TABLE STUDENT (
    USN VARCHAR(10) PRIMARY KEY,
    SName VARCHAR(50) NOT NULL,
    Address TEXT,
    Phone VARCHAR(15),
    Gender CHAR(1) CHECK (Gender IN ('M', 'F'))
);

-- Create the SEMSEC table
CREATE TABLE SEMSEC (
    SSID SERIAL PRIMARY KEY,
    Sem INT NOT NULL,
    Sec CHAR(1) NOT NULL
);

-- Create the CLASS table (Associative entity between STUDENT and SEMSEC)
CREATE TABLE CLASS (
    USN VARCHAR(10),
    SSID INT,
    PRIMARY KEY (USN, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN) ON DELETE CASCADE,
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID) ON DELETE CASCADE
);

-- Create the SUBJECT table
CREATE TABLE SUBJECT (
    Subcode VARCHAR(10) PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Sem INT NOT NULL,
    Credits INT NOT NULL
);

-- Create the IAMARKS table
CREATE TABLE IAMARKS (
    USN VARCHAR(10),
    Subcode VARCHAR(10),
    SSID INT,
    Test1 INT CHECK (Test1 BETWEEN 0 AND 20),
    Test2 INT CHECK (Test2 BETWEEN 0 AND 20),
    Test3 INT CHECK (Test3 BETWEEN 0 AND 20),
    FinalIA INT CHECK (FinalIA BETWEEN 0 AND 20),
    PRIMARY KEY (USN, Subcode, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN) ON DELETE CASCADE,
    FOREIGN KEY (Subcode) REFERENCES SUBJECT(Subcode) ON DELETE CASCADE,
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID) ON DELETE CASCADE
);


