-- Create the DEPARTMENT table first
CREATE TABLE DEPARTMENT (
    DNo SERIAL PRIMARY KEY,
    DName VARCHAR(50) NOT NULL UNIQUE,
    MgrSSN VARCHAR(10),
    MgrStartDate DATE
);

-- Create the DLOCATION table
CREATE TABLE DLOCATION (
    DNo INT,
    DLoc VARCHAR(100) NOT NULL,
    PRIMARY KEY (DNo, DLoc),
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo) ON DELETE CASCADE
);

-- Create the EMPLOYEE table after DEPARTMENT
CREATE TABLE EMPLOYEE (
    SSN VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Address TEXT,
    Sex CHAR(1) CHECK (Sex IN ('M', 'F')),
    Salary DECIMAL(10,2) NOT NULL,
    SuperSSN VARCHAR(10),
    DNo INT,
    FOREIGN KEY (SuperSSN) REFERENCES EMPLOYEE(SSN) ON DELETE SET NULL,
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo) ON DELETE CASCADE
);

-- Update DEPARTMENT table to add foreign key reference after EMPLOYEE is created
ALTER TABLE DEPARTMENT ADD CONSTRAINT fk_manager FOREIGN KEY (MgrSSN) REFERENCES EMPLOYEE(SSN) ON DELETE SET NULL;

-- Create the PROJECT table
CREATE TABLE PROJECT (
    PNo SERIAL PRIMARY KEY,
    PName VARCHAR(100) NOT NULL,
    PLocation VARCHAR(100) NOT NULL,
    DNo INT,
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo) ON DELETE CASCADE
);

-- Create the WORKS_ON table (Many-to-Many Relationship between EMPLOYEE and PROJECT)
CREATE TABLE WORKS_ON (
    SSN VARCHAR(10),
    PNo INT,
    Hours DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (SSN, PNo),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE,
    FOREIGN KEY (PNo) REFERENCES PROJECT(PNo) ON DELETE CASCADE
);
